# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - bash: docker --version
    - bash: docker login -u iamapikey -p tmOs03iOZ7oHVelagO4bzGK2z7Uzy90RmMh3rtzrDxRA us.icr.io
    - bash: docker images
      
      
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: |
    #       $(tag)
