# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - bash: docker --version
    - bash: docker login -u iamapikey -p $(apikey) us.icr.io
    
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: 'us.icr.io/azure-demo/java-test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
