# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: DeployJob
  displayName: DeployJob
  variables:
    project_name: azure-project
  steps:
  # Install oc so that it can be used within a 'script' or bash 'task'
  - task: oc-setup@2
    inputs:
      connectionType: 'OpenShift Connection Service'
      openshiftService: 'roks-cluster'
      version: '3.11.154'
# A script task making use of 'oc'
  - script: |
     oc apply -f $(System.DefaultWorkingDirectory)/openshift/deployment.yaml -n $(project_name)
