apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion-deployment
  namespace: azure-project
spec:
  replicas: 2 
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: us.icr.io/azure-demo/java-test
        name: currency-conversion
---
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: currency-conversion
  name: currency-conversion-service
  namespace: azure-project
spec:
  ports:
  - port: 8100 
    protocol: TCP
    targetPort: 8100 
  selector:
    app: currency-conversion
  type: LoadBalancer